/**
 * Golden-master regression net for the analyzeWhois() field switch.
 *
 * Generated from the full set of case labels present in common_parser.ts.
 * For every label a probe document is parsed and the resulting fields are
 * diffed against initialWhoisAnalyzeResult, so only fields that the switch
 * actually populated appear. Subsequent refactors (label externalisation,
 * extractor split) must keep these snapshots byte-identical.
 *
 * Do NOT hand-edit the snapshots unless an intentional behaviour change is
 * being made and reviewed.
 */
import { describe, it, expect } from "vitest";
import { analyzeWhois } from "./common_parser";
import { initialWhoisAnalyzeResult } from "./types";

const LABELS: string[] = [
  "domain name (unicode)",
  "domain name (ascii)",
  "domain name",
  "domain",
  "nom de domaine",
  "domaine",
  "dominio",
  "domainname",
  "ドメイン名",
  "ドメイン情報",
  "registrar",
  "authorized agency",
  "sponsoring registrar",
  "registrar name",
  "registrar-name",
  "enregistreur",
  "bureau d'enregistrement",
  "注册商",
  "注册服务商",
  "注册机构",
  "registrador",
  "регистратор",
  "iana id",
  "registrar iana id",
  "whois server",
  "whois",
  "registrar whois server",
  "updated date",
  "last updated date",
  "last modified",
  "last-modified",
  "modification date",
  "modified",
  "last update",
  "last updated",
  "update date",
  "date updated",
  "updated on",
  "modified on",
  "date de mise a jour",
  "date de mise à jour",
  "dernière modification",
  "derniere modification",
  "最終更新",
  "zuletzt geaendert am",
  "updated (utc)",
  "last-update",
  "updated",
  "last changed",
  "changed on",
  "modifié le",
  "fecha de modificacion",
  "actualizado",
  "changed",
  "last modification",
  "modified date",
  "last modified date",
  "record last updated",
  "record modified",
  "last update date",
  "domain updated",
  "last-modified-date",
  "senast ändrad",
  "viimeksi muokattu",
  "sist endret",
  "sidst ændret",
  "senest opdateret",
  "letzte änderung",
  "última modificación",
  "última atualização",
  "creation date",
  "registered date",
  "activation",
  "activation date",
  "registered on",
  "date registered",
  "domain registered",
  "created",
  "created on",
  "created date",
  "registration date",
  "registration time",
  "date de creation",
  "date de création",
  "登録年月日",
  "registriert am",
  "datum registracije",
  "created (utc)",
  "created date (utc)",
  "reg date",
  "create date",
  "entry created",
  "domain registration date",
  "first registered",
  "first registration date",
  "registered",
  "register date",
  "start date",
  "date d'enregistrement",
  "enregistré le",
  "fecha de registro",
  "fecha de creacion",
  "fecha creacion",
  "criado em",
  "data de registro",
  "anniversary",
  "inception date",
  "domain inception date",
  "record created",
  "created at",
  "activation time",
  "delegated on",
  "delegated",
  "fecha de alta",
  "registreringsdatum",
  "rekisteröintipäivä",
  "registreringsdato",
  "domainregistrierung",
  "domain name commencement date",
  "domain commencement date",
  "expiration date",
  "expiration",
  "valid until",
  "paid-till",
  "paid till",
  "expires on",
  "expire date",
  "expire",
  "expires",
  "exp date",
  "expiry date",
  "expiry",
  "registry expiration date",
  "date expiration",
  "date d'expiration",
  "有効期限",
  "ablaufdatum",
  "expires (utc)",
  "expiration date (utc)",
  "expiration time",
  "renewal date",
  "due date",
  "valid-date",
  "expire-date",
  "expiration-date",
  "end date",
  "domain expiration date",
  "fecha de vencimiento",
  "fecha expiracion",
  "fecha de expiracion",
  "validade",
  "vence em",
  "ablauf",
  "laufzeit bis",
  "registry expiry date",
  "registrar registration expiration date",
  "registration expiry date",
  "expiration-date (registrar)",
  "domain renewal date",
  "renewal deadline",
  "validity",
  "validity date",
  "valid through",
  "valid to",
  "valid-till",
  "gyldig til",
  "keston loppupäivä",
  "giltig till",
  "verfallsdatum",
  "state",
  "status",
  "registration status",
  "statut",
  "estado",
  "状態",
  "ロック状態",
  "domain status",
  "name server",
  "name server (db)",
  "host name",
  "hostname",
  "nameserver",
  "ネームサーバ",
  "serveur de noms",
  "servidor de nombres",
  "ns",
  "ns1",
  "ns2",
  "ns3",
  "ns4",
  "ns5",
  "ns6",
  "dns",
  "dns1",
  "dns2",
  "dns3",
  "dns4",
  "primary nameserver",
  "secondary nameserver",
  "serveur dns",
  "nameservers",
  "name servers",
  "nserver",
  "primary server",
  "secondary server",
  "p",
  "registry domain id",
  "domain id",
  "domain-id",
  "roid",
  "registrant name",
  "registrant contact name",
  "holder",
  "owner",
  "nom",
  "nombre",
  "personname",
  "登録者名",
  "名前",
  "注册者",
  "注册人",
  "域名持有者",
  "持有人",
  "主办单位名称",
  "организация-владелец",
  "name",
  "registrant organization",
  "registrant organisation",
  "registrant org",
  "domain holder organization",
  "注册单位",
  "主办单位",
  "организация",
  "organization",
  "organisation",
  "org-name",
  "registrant",
  "descr",
  "registrant state/province",
  "registrant state",
  "registrant province",
  "province",
  "省/市",
  "省份",
  "registrant city",
  "registrant locality",
  "city",
  "locality",
  "ville",
  "ciudad",
  "市",
  "城市",
  "cidade",
  "registrant street",
  "registrant address",
  "registrant street1",
  "registrant street2",
  "registrant street3",
  "street",
  "address",
  "addr",
  "adresse",
  "direccion",
  "street address",
  "domain holder street",
  "通讯地址",
  "联系地址",
  "详细地址",
  "postal address",
  "住所",
  "registrant postal code",
  "registrant zip",
  "registrant zip code",
  "postal code",
  "code postal",
  "zip code",
  "zip",
  "postcode",
  "postalcode",
  "postal-code",
  "邮政编码",
  "邮编",
  "codigo postal",
  "registrant country",
  "registrant country code",
  "registrant country/economy",
  "国家/地区",
  "国家",
  "pais",
  "country",
  "country-code",
  "pays",
  "domain holder country",
  "registrant phone",
  "registrant phone number",
  "registrant telephone",
  "phone",
  "telephone",
  "téléphone",
  "telefono",
  "联系电话",
  "telefone",
  "телефон",
  "registrant fax",
  "registrant fax ext",
  "fax",
  "fax-no",
  "fax no",
  "telefax",
  "admin name",
  "administrative name",
  "admin contact name",
  "admin contact",
  "administrative contact",
  "administrative contact name",
  "ac",
  "admin id",
  "admin organization",
  "admin organisation",
  "admin org",
  "administrative organization",
  "administrative organisation",
  "admin email",
  "admin e-mail",
  "administrative email",
  "administrative e-mail",
  "admin contact email",
  "ac e-mail",
  "admin phone",
  "admin telephone",
  "administrative phone",
  "administrative telephone",
  "admin contact phone",
  "admin country",
  "administrative country",
  "tech name",
  "technical name",
  "technical contact name",
  "tech contact name",
  "tech contact",
  "technical contact",
  "tech organization",
  "tech organisation",
  "tech org",
  "technical organization",
  "technical organisation",
  "tech email",
  "tech e-mail",
  "technical email",
  "technical e-mail",
  "tech contact email",
  "tech phone",
  "tech telephone",
  "technical phone",
  "technical telephone",
  "tech contact phone",
  "registrar abuse contact phone",
  "abuse phone",
  "abuse contact phone",
  "registrar abuse contact email",
  "abuse-mailbox",
  "orgtechphone",
  "registrant email",
  "registrant contact email",
  "注册者联系人邮箱",
  "注册者邮箱",
  "dnssec",
  "dnssec status",
  "signed",
  "email",
  "电子邮件",
  "邮箱",
  "联系人邮箱",
  "e-mail",
  "courriel",
  "registrar url",
  "referral url",
  "registrar website",
  "cidr",
  "inetnum",
  "inet6num",
  "netrange",
  "netname",
  "network-name",
  "nettype",
  "originas",
  "origin",
];

function probeFor(label: string): string {
  const l = label.toLowerCase();
  if (/date|jour|datum|fecha|data|päivä|dag|dato|geaendert|ändrad|muokattu|endret|ændret|opdateret|modificat|actualiz|modifié|ablauf|laufzeit|verfall|gyldig|giltig|keston|validity|valid|expir|renewal|due|anniversary|inception|delegated|activation|registrerings|rekisteröinti|domainregistrierung/.test(l))
    return "2020-01-15";
  if (/mail|courriel|correo/.test(l)) return "user@example.com";
  if (/server|nameserver|\bdns\b|dns[1-4]|\bns\b|ns[1-6]|nserver|\bhost\b|hostname|\bp\b/.test(l))
    return "ns1.example.com";
  if (/status|state|statut|estado|状態/.test(l)) return "clientTransferProhibited";
  if (/phone|telephone|tel|fax|telefon|telefax|téléphone/.test(l)) return "+1.5551234567";
  if (/country|pays|pais|国家/.test(l)) return "US";
  if (/url|website/.test(l)) return "http://example.com";
  if (/id$|\bid\b/.test(l)) return "1234";
  if (/street|address|addr|adresse|direccion|住所|地址/.test(l)) return "1 Example Street";
  if (/city|locality|ville|ciudad|cidade|市/.test(l)) return "Exampleville";
  if (/province|省/.test(l)) return "Example Province";
  if (/postal|zip|postcode|邮编/.test(l)) return "12345";
  if (/dnssec|signed/.test(l)) return "unsigned";
  if (/cidr/.test(l)) return "192.0.2.0/24";
  if (/inetnum|inet6num|netrange/.test(l)) return "192.0.2.0 - 192.0.2.255";
  if (/netname|network-name/.test(l)) return "EXAMPLE-NET";
  if (/nettype/.test(l)) return "ALLOCATED";
  if (/originas|origin/.test(l)) return "AS64500";
  if (/organization|organisation|org|организация|注册单位|主办单位/.test(l)) return "Example Org";
  if (/registrar|注册商|регистратор|registrador|enregistreur/.test(l)) return "Example Registrar";
  if (/domain|domaine|dominio|ドメイン|域名/.test(l)) return "probe.example";
  return "Probe Value";
}

/** applyParams-derived fields are not part of the switch under test. */
const DERIVED = new Set([
  "rawWhoisContent",
  "domainPunycode",
  "registerPrice",
  "renewPrice",
  "negotiable",
  "domainAge",
  "remainingDays",
]);

const DEFAULTS = initialWhoisAnalyzeResult as unknown as Record<string, unknown>;

function diffFromDefaults(r: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(r)) {
    if (DERIVED.has(k)) continue;
    const def = DEFAULTS[k];
    if (Array.isArray(v)) {
      if (v.length === 0) continue;
      if (Array.isArray(def) && JSON.stringify(v) === JSON.stringify(def)) continue;
      out[k] = v;
      continue;
    }
    if (v === def) continue;
    if (v === undefined || v === null || v === false) continue;
    out[k] = v;
  }
  return out;
}

describe("analyzeWhois — golden master over every switch label", () => {
  it("parses each label with stable output", async () => {
    const seen: Record<string, unknown> = {};
    for (const label of LABELS) {
      const doc = `Domain Name: probe.example\n${label}: ${probeFor(label)}\n`;
      const r = await analyzeWhois(doc);
      seen[label] = diffFromDefaults(r as unknown as Record<string, unknown>);
    }
    expect(seen).toMatchSnapshot();
  });
});
