/**
 * rdap-bootstrap.ts — self-hosted replacement for node-rdap's IANA bootstrap.
 *
 * node-rdap fetched https://data.iana.org/rdap/{dns,ipv4,ipv6,asn}.json at
 * runtime to discover RDAP servers.  We replaced the dns.json path with the
 * static GTLD_RDAP_BOOTSTRAP + CCTLD_RDAP_OVERRIDES maps (see rdap_client.ts).
 * This module replaces the ipv4/ipv6/asn.json paths with the static
 * src/data/rdap-bootstrap.json — the same 5 RIR servers (AFRINIC, APNIC,
 * ARIN, RIPE, LACNIC) are used, so behaviour is identical without any
 * network round-trip at query time.
 *
 * The static file is regenerated by: node scripts/update-rdap-ip-asn-bootstrap.js
 */
import { matches } from "ip-matching";
import rdapBootstrap from "@/data/rdap-bootstrap.json";

type BootstrapService = [string[], string[]];

const IPV4_SERVICES = rdapBootstrap.services.ipv4 as BootstrapService[];
const IPV6_SERVICES = rdapBootstrap.services.ipv6 as BootstrapService[];
const ASN_SERVICES = rdapBootstrap.services.asn as BootstrapService[];

function normalizeServer(server: string): string {
  return server.endsWith("/") ? server.slice(0, -1) : server;
}

function findServerForMask(
  services: BootstrapService[],
  value: string,
  matcher: (value: string, mask: string) => boolean,
): string | null {
  for (const [blocks, servers] of services) {
    for (const block of blocks) {
      try {
        if (matcher(value, block)) {
          return servers[0] ? normalizeServer(servers[0]) : null;
        }
      } catch {
        // Invalid IP string (e.g. "999.999.999.999") — ip-matching throws
        // instead of returning false.  Treat as no-match.
        return null;
      }
    }
  }
  return null;
}

/** Returns the RDAP base URL for an IPv4 address, or null. */
export function getRdapServerForIpv4(ip: string): string | null {
  return findServerForMask(IPV4_SERVICES, ip, matches);
}

/** Returns the RDAP base URL for an IPv6 address, or null. */
export function getRdapServerForIpv6(ip: string): string | null {
  return findServerForMask(IPV6_SERVICES, ip, matches);
}

/** Returns the RDAP base URL for an AS number, or null. */
export function getRdapServerForAsn(asn: number): string | null {
  return findServerForMask(ASN_SERVICES, String(asn), (asnStr, range) => {
    const [start, end] = range.split("-").map(Number);
    const value = Number(asnStr);
    return value >= start && value <= end;
  });
}

/**
 * Maps an RIR RDAP hostname to that RIR's TCP WHOIS hostname.  Each of the 5
 * RIRs runs both an RDAP service and a WHOIS server on a fixed hostname, so
 * given a local RDAP server we can derive the WHOIS server without a
 * whois.iana.org round-trip.
 *
 * Returns null for unknown/unrecognised RDAP hosts.
 */
export function getWhoisHostForRdap(rdapHost: string): string | null {
  const lower = rdapHost.toLowerCase().replace(/^https?:\/\//, "");
  const domain = lower.split("/")[0];
  const map: Record<string, string> = {
    "rdap.arin.net": "whois.arin.net",
    "rdap.db.ripe.net": "whois.ripe.net",
    "rdap.apnic.net": "whois.apnic.net",
    "rdap.lacnic.net": "whois.lacnic.net",
    "rdap.afrinic.net": "whois.afrinic.net",
  };
  return map[domain] ?? null;
}
