/**
 * Static WHOIS server bootstrap — only TLDs without RDAP support.
 * TLDs with RDAP are in rdap_gtld_bootstrap.ts; those take priority.
 * If a TLD is not in this list, the app falls back to IANA WHOIS auto-discovery.
 *
 * Updated: 2026-04-01
 * Entries: 119
 */
export const GTLD_WHOIS_BOOTSTRAP: Record<string, string> = {
  "ac": "whois.nic.ac",
  "ae": "whois.aeda.net.ae",
  "af": "whois.nic.af",
  "al": "whois.nic.al",
  "arpa": "whois.iana.org",
  "az": "whois.nic.az",
  "ba": "whois.nic.ba",
  "bb": "whois.nic.bb",
  "bd": "whois.btcl.net.bt",
  "bh": "whois.nic.bh",
  "bn": "whois.bnnic.bn",
  "bo": "whois.nic.bo",
  "bt": "whois.nic.bt",
  "bw": "whois.nic.bw",
  "by": "whois.cctld.by",
  "cd": "whois.nic.cd",
  "ci": "whois.nic.ci",
  "cl": "whois.nic.cl",
  "cn": "whois.cnnic.cn",
  "co": "whois.cctld.co",
  "cu": "whois.nic.cu",
  "cy": "whois.nic.cy",
  "de": "whois.denic.de",
  "dj": "whois.nic.dj",
  "dk": "whois.punktum.dk",
  "dm": "whois.nic.dm",
  "do": "whois.nic.do",
  "edu": "whois.educause.edu",
  "ee": "whois.tld.ee",
  "eg": "whois.ripe.net",
  "es": "whois.nic.es",
  "et": "whois.nic.et",
  "ge": "whois.nic.ge",
  "gh": "whois.nic.gh",
  "gl": "whois.nic.gl",
  "gr": "whois.ics.forth.gr",
  "gt": "whois.nic.gt",
  "hk": "whois.hkirc.hk",
  "hr": "whois.dns.hr",
  "hu": "whois.nic.hu",
  "il": "whois.isoc.org.il",
  "im": "whois.nic.im",
  "iq": "whois.cmc.iq",
  "it": "whois.nic.it",
  "jm": "whois.nic.jm",
  "jo": "whois.dns.jo",
  "jp": "whois.jprs.jp",
  "kh": "whois.nic.kh",
  "kn": "whois.nic.kn",
  "kr": "whois.kr",
  "kz": "whois.nic.kz",
  "la": "whois.nic.la",
  "li": "whois.nic.li",
  "lk": "whois.nic.lk",
  "lt": "whois.domreg.lt",
  "lu": "whois.dns.lu",
  "lv": "whois.nic.lv",
  "ma": "whois.registre.ma",
  "md": "whois.nic.md",
  "me": "whois.nic.me",
  "mk": "whois.nic.mk",
  "mm": "whois.nic.mm",
  "mt": "whois.nic.mt",
  "mv": "whois.nic.mv",
  "mw": "whois.nic.mw",
  "mx": "whois.mx",
  "my": "whois.mynic.my",
  "mz": "whois.nic.mz",
  "ni": "whois.nic.ni",
  "np": "whois.mos.com.np",
  "nu": "whois.iis.nu",
  "nz": "whois.srs.net.nz",
  "om": "whois.registry.om",
  "pa": "whois.nic.pa",
  "pe": "whois.nic.pe",
  "ph": "whois.dot.ph",
  "pk": "whois.pknic.net.pk",
  "pr": "whois.afilias-srs.net",
  "ps": "whois.pnina.ps",
  "py": "whois.nic.py",
  "ro": "whois.rotld.ro",
  "rs": "whois.rnids.rs",
  "ru": "whois.tcinet.ru",
  "sa": "whois.nic.net.sa",
  "sb": "whois.nic.sb",
  "sc": "whois.nic.sc",
  "se": "whois.iis.se",
  "sh": "whois.nic.sh",
  "sk": "whois.sk-nic.sk",
  "so": "whois.nic.so",
  "su": "whois.tcinet.ru",
  "sv": "whois.nic.sv",
  "sy": "whois.tld.sy",
  "td": "whois.nic.td",
  "tj": "whois.nic.tj",
  "tl": "whois.nic.tl",
  "tm": "whois.nic.tm",
  "tr": "whois.nic.tr",
  "tt": "whois.nic.tt",
  "ug": "whois.nic.ug",
  "us": "whois.nic.us",
  "uy": "whois.nic.org.uy",
  "ve": "whois.nic.ve",
  "vn": "whois.vnnic.vn",
  "vu": "whois.nic.vu",
  "ws": "whois.nic.ws",
  "xk": "whois.nic.xk",
  "xn--5dbq4a": "whois.iam.net.ma",
  "xn--fiqs8sirgfmh": "whois.cnnic.cn",
  "xn--fiqz9s": "whois.cnnic.cn",
  "xn--lgbbat1ad8j": "whois.nic.dz",
  "xn--mgb9awbf": "whois.registry.om",
  "xn--mgberp4a5d4ar": "whois.nic.net.sa",
  "xn--mix082f": "whois.monic.mo",
  "xn--mix891f": "whois.monic.mo",
  "xn--pgbs0dh": "whois.registre.tn",
  "xn--wgbl6a": "whois.registry.qa",
  "za": "whois.registry.net.za",
  "zw": "whois.zispa.co.zw",
};

/** Look up the WHOIS server hostname for a given TLD (returns undefined if not known). */
export function getGtldWhoisServer(tld: string): string | undefined {
  return GTLD_WHOIS_BOOTSTRAP[tld.toLowerCase()];
}
