/**
 * Multilingual / variant WHOIS field-label aliases.
 *
 * WHOIS registries worldwide emit the same logical field under many labels —
 * English synonyms, localised translations (Chinese, Japanese, Russian,
 * Portuguese, Spanish, French, German, Nordic) and registry-specific spellings.
 * analyzeWhois() normalises every incoming label through LABEL_ALIASES before
 * dispatching, so the field switch only needs to list one canonical label per
 * field instead of every localised variant.
 *
 * The canonical labels here MUST match a `case` in common_parser.ts.
 * Behaviour for each alias is locked by common-parser-golden.test.ts.
 */
export const LABEL_ALIASES: Readonly<Record<string, string>> = {
  "ablauf": "expiration date",
  "ablaufdatum": "expiration date",
  "abuse contact phone": "registrar abuse contact phone",
  "abuse phone": "registrar abuse contact phone",
  "abuse-mailbox": "registrar abuse contact email",
  "ac": "admin name",
  "ac e-mail": "admin email",
  "activation": "creation date",
  "activation date": "creation date",
  "activation time": "creation date",
  "actualizado": "updated date",
  "addr": "registrant street",
  "address": "registrant street",
  "admin contact": "admin name",
  "admin contact email": "admin email",
  "admin contact name": "admin name",
  "admin contact phone": "admin phone",
  "admin e-mail": "admin email",
  "admin id": "admin name",
  "admin org": "admin organization",
  "admin organisation": "admin organization",
  "admin telephone": "admin phone",
  "administrative contact": "admin name",
  "administrative contact name": "admin name",
  "administrative country": "admin country",
  "administrative e-mail": "admin email",
  "administrative email": "admin email",
  "administrative name": "admin name",
  "administrative organisation": "admin organization",
  "administrative organization": "admin organization",
  "administrative phone": "admin phone",
  "administrative telephone": "admin phone",
  "adresse": "registrant street",
  "anniversary": "creation date",
  "authorized agency": "registrar",
  "bureau d'enregistrement": "registrar",
  "changed": "updated date",
  "changed on": "updated date",
  "cidade": "registrant city",
  "city": "registrant city",
  "ciudad": "registrant city",
  "code postal": "registrant postal code",
  "codigo postal": "registrant postal code",
  "country-code": "country",
  "courriel": "email",
  "create date": "creation date",
  "created": "creation date",
  "created (utc)": "creation date",
  "created at": "creation date",
  "created date": "creation date",
  "created date (utc)": "creation date",
  "created on": "creation date",
  "criado em": "creation date",
  "data de registro": "creation date",
  "date d'enregistrement": "creation date",
  "date d'expiration": "expiration date",
  "date de creation": "creation date",
  "date de création": "creation date",
  "date de mise a jour": "updated date",
  "date de mise à jour": "updated date",
  "date expiration": "expiration date",
  "date registered": "creation date",
  "date updated": "updated date",
  "datum registracije": "creation date",
  "delegated": "creation date",
  "delegated on": "creation date",
  "derniere modification": "updated date",
  "dernière modification": "updated date",
  "direccion": "registrant street",
  "dns": "name server",
  "dns1": "name server",
  "dns2": "name server",
  "dns3": "name server",
  "dns4": "name server",
  "dnssec status": "dnssec",
  "domain": "domain name",
  "domain commencement date": "domain name commencement date",
  "domain expiration date": "expiration date",
  "domain holder country": "country",
  "domain holder organization": "registrant organization",
  "domain holder street": "registrant street",
  "domain id": "registry domain id",
  "domain inception date": "creation date",
  "domain registered": "creation date",
  "domain registration date": "creation date",
  "domain renewal date": "expiration date",
  "domain updated": "updated date",
  "domain-id": "registry domain id",
  "domaine": "domain name",
  "domainname": "domain name",
  "domainregistrierung": "creation date",
  "dominio": "domain name",
  "due date": "expiration date",
  "e-mail": "email",
  "end date": "expiration date",
  "enregistreur": "registrar",
  "enregistré le": "creation date",
  "entry created": "creation date",
  "estado": "status",
  "exp date": "expiration date",
  "expiration": "expiration date",
  "expiration date (utc)": "expiration date",
  "expiration time": "expiration date",
  "expiration-date": "expiration date",
  "expiration-date (registrar)": "expiration date",
  "expire": "expiration date",
  "expire date": "expiration date",
  "expire-date": "expiration date",
  "expires": "expiration date",
  "expires (utc)": "expiration date",
  "expires on": "expiration date",
  "expiry": "expiration date",
  "expiry date": "expiration date",
  "fax": "registrant fax",
  "fax no": "registrant fax",
  "fax-no": "registrant fax",
  "fecha creacion": "creation date",
  "fecha de alta": "creation date",
  "fecha de creacion": "creation date",
  "fecha de expiracion": "expiration date",
  "fecha de modificacion": "updated date",
  "fecha de registro": "creation date",
  "fecha de vencimiento": "expiration date",
  "fecha expiracion": "expiration date",
  "first registered": "creation date",
  "first registration date": "creation date",
  "giltig till": "expiration date",
  "gyldig til": "expiration date",
  "holder": "registrant name",
  "host name": "name server",
  "hostname": "name server",
  "inception date": "creation date",
  "keston loppupäivä": "expiration date",
  "last changed": "updated date",
  "last modification": "updated date",
  "last modified": "updated date",
  "last modified date": "updated date",
  "last update": "updated date",
  "last update date": "updated date",
  "last updated": "updated date",
  "last updated date": "updated date",
  "last-modified": "updated date",
  "last-modified-date": "updated date",
  "last-update": "updated date",
  "laufzeit bis": "expiration date",
  "letzte änderung": "updated date",
  "locality": "registrant city",
  "modification date": "updated date",
  "modified": "updated date",
  "modified date": "updated date",
  "modified on": "updated date",
  "modifié le": "updated date",
  "name": "registrant name",
  "name server (db)": "name server",
  "name servers": "name server",
  "nameserver": "name server",
  "nameservers": "name server",
  "nom": "registrant name",
  "nom de domaine": "domain name",
  "nombre": "registrant name",
  "ns": "name server",
  "ns1": "name server",
  "ns2": "name server",
  "ns3": "name server",
  "ns4": "name server",
  "ns5": "name server",
  "ns6": "name server",
  "nserver": "name server",
  "org-name": "organization",
  "organisation": "organization",
  "owner": "registrant name",
  "p": "name server",
  "paid till": "expiration date",
  "paid-till": "expiration date",
  "pais": "registrant country",
  "pays": "country",
  "personname": "registrant name",
  "phone": "registrant phone",
  "postal address": "registrant street",
  "postal code": "registrant postal code",
  "postal-code": "registrant postal code",
  "postalcode": "registrant postal code",
  "postcode": "registrant postal code",
  "primary nameserver": "name server",
  "primary server": "name server",
  "province": "registrant state/province",
  "record created": "creation date",
  "record last updated": "updated date",
  "record modified": "updated date",
  "referral url": "registrar url",
  "reg date": "creation date",
  "register date": "creation date",
  "registered": "creation date",
  "registered date": "creation date",
  "registered on": "creation date",
  "registrador": "registrar",
  "registrant address": "registrant street",
  "registrant contact email": "registrant email",
  "registrant contact name": "registrant name",
  "registrant country code": "registrant country",
  "registrant country/economy": "registrant country",
  "registrant fax ext": "registrant fax",
  "registrant locality": "registrant city",
  "registrant org": "registrant organization",
  "registrant organisation": "registrant organization",
  "registrant phone number": "registrant phone",
  "registrant province": "registrant state/province",
  "registrant state": "registrant state/province",
  "registrant street1": "registrant street",
  "registrant street2": "registrant street",
  "registrant street3": "registrant street",
  "registrant telephone": "registrant phone",
  "registrant zip": "registrant postal code",
  "registrant zip code": "registrant postal code",
  "registrar name": "registrar",
  "registrar registration expiration date": "expiration date",
  "registrar website": "registrar url",
  "registrar-name": "registrar",
  "registration date": "creation date",
  "registration expiry date": "expiration date",
  "registration status": "status",
  "registration time": "creation date",
  "registreringsdato": "creation date",
  "registreringsdatum": "creation date",
  "registriert am": "creation date",
  "registry expiration date": "expiration date",
  "registry expiry date": "expiration date",
  "rekisteröintipäivä": "creation date",
  "renewal date": "expiration date",
  "renewal deadline": "expiration date",
  "roid": "registry domain id",
  "secondary nameserver": "name server",
  "secondary server": "name server",
  "senast ändrad": "updated date",
  "senest opdateret": "updated date",
  "serveur de noms": "name server",
  "serveur dns": "name server",
  "servidor de nombres": "name server",
  "sidst ændret": "updated date",
  "signed": "dnssec",
  "sist endret": "updated date",
  "sponsoring registrar": "registrar",
  "start date": "creation date",
  "statut": "status",
  "street": "registrant street",
  "street address": "registrant street",
  "tech contact": "tech name",
  "tech contact email": "tech email",
  "tech contact name": "tech name",
  "tech contact phone": "tech phone",
  "tech e-mail": "tech email",
  "tech org": "tech organization",
  "tech organisation": "tech organization",
  "tech telephone": "tech phone",
  "technical contact": "tech name",
  "technical contact name": "tech name",
  "technical e-mail": "tech email",
  "technical email": "tech email",
  "technical name": "tech name",
  "technical organisation": "tech organization",
  "technical organization": "tech organization",
  "technical phone": "tech phone",
  "technical telephone": "tech phone",
  "telefax": "registrant fax",
  "telefone": "registrant phone",
  "telefono": "registrant phone",
  "telephone": "registrant phone",
  "téléphone": "registrant phone",
  "update date": "updated date",
  "updated": "updated date",
  "updated (utc)": "updated date",
  "updated on": "updated date",
  "valid through": "expiration date",
  "valid to": "expiration date",
  "valid until": "expiration date",
  "valid-date": "expiration date",
  "valid-till": "expiration date",
  "validade": "expiration date",
  "validity": "expiration date",
  "validity date": "expiration date",
  "vence em": "expiration date",
  "verfallsdatum": "expiration date",
  "viimeksi muokattu": "updated date",
  "ville": "registrant city",
  "zip": "registrant postal code",
  "zip code": "registrant postal code",
  "zuletzt geaendert am": "updated date",
  "última atualização": "updated date",
  "última modificación": "updated date",
  "организация": "registrant organization",
  "организация-владелец": "registrant name",
  "регистратор": "registrar",
  "телефон": "registrant phone",
  "ドメイン情報": "domain name",
  "ドメイン名": "domain name",
  "ネームサーバ": "name server",
  "ロック状態": "status",
  "主办单位": "registrant organization",
  "主办单位名称": "registrant name",
  "住所": "registrant street",
  "名前": "registrant name",
  "国家": "registrant country",
  "国家/地区": "registrant country",
  "城市": "registrant city",
  "域名持有者": "registrant name",
  "市": "registrant city",
  "持有人": "registrant name",
  "最終更新": "updated date",
  "有効期限": "expiration date",
  "注册人": "registrant name",
  "注册单位": "registrant organization",
  "注册商": "registrar",
  "注册服务商": "registrar",
  "注册机构": "registrar",
  "注册者": "registrant name",
  "注册者联系人邮箱": "registrant email",
  "注册者邮箱": "registrant email",
  "状態": "status",
  "电子邮件": "email",
  "登録年月日": "creation date",
  "登録者名": "registrant name",
  "省/市": "registrant state/province",
  "省份": "registrant state/province",
  "联系人邮箱": "email",
  "联系地址": "registrant street",
  "联系电话": "registrant phone",
  "详细地址": "registrant street",
  "通讯地址": "registrant street",
  "邮政编码": "registrant postal code",
  "邮箱": "email",
  "邮编": "registrant postal code",
};
